#!/bin/sh
dir=$1
prog=$2
ldc2 -I=$(dirname $dir) -i=. -i=object -c -release --enable-inlining -Oz -betterC -conf= -od=$dir/out/obj_$prog $(dirname $dir)/$prog.d
ld -o $dir/out/$prog $dir/out/obj_$prog/*.o
